# Generated by Django 5.2.6 on 2025-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_charactires'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentcharacteristics',
            name='score',
            field=models.FloatField(blank=True, help_text='Оценка соответствия характеристике (от 0 до 1)', null=True),
        ),
    ]
