# Generated by Django 5.2.6 on 2025-10-07 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_users_is_active_users_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('characteristic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value_type', models.CharField(choices=[('string', 'Строковое значение'), ('numeric', 'Числовое значение'), ('choice', 'Выбор из списка')], default='string', help_text='Тип значения характеристики (числовое, строковое или выбор)', max_length=20)),
                ('requirements', models.TextField(blank=True, help_text='Текстовые требования или описание допустимых значений', null=True)),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'db_table': 'characteristics',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValues',
            fields=[
                ('characteristic_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value_text', models.CharField(max_length=255)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='accounts.characteristics')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'db_table': 'characteristic_values',
            },
        ),
        migrations.CreateModel(
            name='RespondentCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.characteristicvalues')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Характеристика респондента',
                'verbose_name_plural': 'Характеристики респондентов',
                'db_table': 'respondent_characteristics',
                'unique_together': {('user', 'characteristic_value')},
            },
        ),
    ]
