# Generated by Django 5.2.6 on 2025-10-15 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_diagram', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('data_diagram', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.questions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='surveys.surveys')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='AnswerReliability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reliability_score', models.FloatField(default=0.0)),
                ('is_reliable', models.BooleanField(default=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
            options={
                'verbose_name': 'Оценка достоверности ответа',
                'verbose_name_plural': 'Оценки достоверности ответов',
                'db_table': 'answer_reliability',
            },
        ),
        migrations.CreateModel(
            name='ClusterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.CharField(max_length=100)),
                ('respondent_ids', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_x', models.CharField(max_length=255)),
                ('variable_y', models.CharField(max_length=255)),
                ('correlation_coefficient', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Основной дашборд', max_length=255)),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Структура расположения блоков (chart/table и т.п.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='surveys.surveys')),
            ],
            options={
                'verbose_name': 'Дашборд',
                'verbose_name_plural': 'Дашборды',
                'db_table': 'dashboards',
            },
        ),
    ]
