# Generated by Django 5.2.6 on 2025-10-15 09:22

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_question', models.TextField()),
                ('type_question', models.CharField(choices=[('text', 'Текст'), ('single_choice', 'Одиночный выбор'), ('multi_choice', 'Множественный выбор'), ('checkbox', 'Чекбоксы'), ('dropdown', 'Выпадающий список'), ('likert', 'Шкала Лайкерта'), ('rating', 'Рейтинг'), ('date_time', 'Дата/время')], default='text', max_length=50)),
                ('extra_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('max_residents', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('stopped', 'Stopped'), ('finished', 'Finished')], default='draft', max_length=20)),
                ('type_survey', models.CharField(choices=[('simple', 'Простой'), ('extended', 'Расширенный')], default='simple', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость (или вознаграждение) за прохождение опроса', max_digits=10, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('survey_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='surveys.questions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='surveys.surveys')),
            ],
            options={
                'db_table': 'survey_questions',
                'managed': True,
                'unique_together': {('survey', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SurveyArchive',
            fields=[
                ('archive_id', models.AutoField(primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived_copy', to='surveys.surveys')),
            ],
            options={
                'db_table': 'survey_archive',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RespondentAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestions')),
            ],
            options={
                'db_table': 'respondent_answers',
                'managed': True,
                'unique_together': {('survey_question', 'respondent')},
            },
        ),
        migrations.CreateModel(
            name='RespondentSurveyStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Пройден')], default='in_progress', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='Оценка качества прохождения опроса (0.0–1.0)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_statuses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_statuses', to='surveys.surveys')),
            ],
            options={
                'db_table': 'respondent_survey_status',
                'managed': True,
                'unique_together': {('respondent', 'survey')},
            },
        ),
    ]
