# Generated by Django 5.2.6 on 2025-09-22 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_question', models.TextField()),
                ('type_question', models.CharField(default='text', max_length=50)),
            ],
            options={
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('max_residents', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('stopped', 'Stopped'), ('finished', 'Finished')], default='draft', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('survey_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='surveys.questions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='surveys.surveys')),
            ],
            options={
                'db_table': 'survey_questions',
                'managed': True,
                'unique_together': {('survey', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RespondentAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestions')),
            ],
            options={
                'db_table': 'respondent_answers',
                'managed': True,
                'unique_together': {('survey_question', 'respondent')},
            },
        ),
    ]
