# Generated by Django 5.2.6 on 2025-10-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость (или вознаграждение) за прохождение опроса', max_digits=10, null=True),
        ),
    ]
