# Generated by Django 5.2.6 on 2025-10-02 11:14

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='extra_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='surveys',
            name='type_survey',
            field=models.CharField(choices=[('simple', 'Простой'), ('extended', 'Расширенный')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type_question',
            field=models.CharField(choices=[('text', 'Текст'), ('single_choice', 'Одиночный выбор'), ('multi_choice', 'Множественный выбор'), ('checkbox', 'Чекбоксы'), ('dropdown', 'Выпадающий список'), ('likert', 'Шкала Лайкерта'), ('rating', 'Рейтинг'), ('date_time', 'Дата/время')], default='text', max_length=50),
        ),
        migrations.CreateModel(
            name='SurveyArchive',
            fields=[
                ('archive_id', models.AutoField(primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archived_copy', to='surveys.surveys')),
            ],
            options={
                'db_table': 'survey_archive',
                'managed': True,
            },
        ),
    ]
