# Generated by Django 5.2.6 on 2025-10-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveys_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentsurveystatus',
            name='score',
            field=models.FloatField(blank=True, help_text='Оценка качества прохождения опроса (0.0–1.0)', null=True),
        ),
    ]
