# Generated by Django 5.2.6 on 2025-10-05 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_questions_extra_data_surveys_type_survey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentSurveyStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Пройден')], default='in_progress', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_statuses', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_statuses', to='surveys.surveys')),
            ],
            options={
                'db_table': 'respondent_survey_status',
                'managed': True,
                'unique_together': {('respondent', 'survey')},
            },
        ),
    ]
