# Generated by Django 5.2.6 on 2025-10-19 16:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_wallet',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('topup', 'Пополнение'), ('withdraw', 'Вывод'), ('payout', 'Выплата респонденту'), ('commission', 'Комиссия платформы'), ('refund', 'Возврат')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_survey_id', models.IntegerField(blank=True, null=True)),
                ('related_respondent_id', models.IntegerField(blank=True, null=True)),
                ('gateway_data', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'indexes': [models.Index(fields=['user', 'type'], name='payment_tra_user_id_a2d8de_idx'), models.Index(fields=['related_survey_id', 'related_respondent_id'], name='payment_tra_related_c61a7a_idx')],
            },
        ),
    ]
