# Generated by Django 5.2.6 on 2025-10-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRequiredCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(blank=True, help_text='Дополнительные условия для характеристики', null=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_surveys', to='accounts.characteristics')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_characteristics', to='surveys.surveys')),
            ],
            options={
                'verbose_name': 'Требуемая характеристика опроса',
                'verbose_name_plural': 'Требуемые характеристики опросов',
                'db_table': 'survey_required_characteristics',
                'unique_together': {('survey', 'characteristic')},
            },
        ),
    ]
