# Generated by Django 5.2.6 on 2025-10-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagram_id', models.IntegerField(blank=True, null=True)),
                ('type_diagram', models.CharField(blank=True, max_length=255, null=True)),
                ('data_diagram', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
            options={
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_n', models.IntegerField()),
                ('column_n', models.IntegerField()),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
            options={
                'db_table': 'dashboards',
            },
        ),
    ]
