# Generated by Django 5.2.6 on 2025-09-27 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('characteristic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'characteristics',
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagram_id', models.IntegerField(blank=True, null=True)),
                ('type_diagram', models.CharField(blank=True, max_length=255, null=True)),
                ('data_diagram', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.questions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
            options={
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValues',
            fields=[
                ('characteristic_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value_text', models.CharField(max_length=255)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.characteristics')),
            ],
            options={
                'db_table': 'characteristic_values',
            },
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_n', models.IntegerField()),
                ('column_n', models.IntegerField()),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
            options={
                'db_table': 'dashboards',
            },
        ),
        migrations.CreateModel(
            name='RespondentCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.characteristicvalues')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respondent_characteristics',
                'unique_together': {('user', 'characteristic_value')},
            },
        ),
    ]
