# Generated by Django 5.2.6 on 2025-09-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagram_id', models.IntegerField(blank=True, null=True)),
                ('type_diagram', models.CharField(blank=True, max_length=255, null=True)),
                ('data_diagram', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('characteristic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'characteristics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacteristicValues',
            fields=[
                ('characteristic_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value_text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'characteristic_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_n', models.IntegerField()),
                ('column_n', models.IntegerField()),
            ],
            options={
                'db_table': 'dashboards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_question', models.TextField()),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespondentAnswers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_answer', models.TextField()),
            ],
            options={
                'db_table': 'respondent_answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespondentCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'respondent_characteristics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('survey_question_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'survey_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('max_residents', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'surveys',
                'managed': False,
            },
        ),
    ]
