# Generated by Django 5.2.6 on 2025-10-11 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_respondentcharacteristics_score'),
        ('core', '0001_initial'),
        ('surveys', '0002_surveys_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRequiredCharacteristics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=True, help_text='Обязательна ли характеристика для участия')),
                ('characteristic', models.ForeignKey(help_text='Характеристика, требуемая для прохождения опроса', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_surveys', to='accounts.characteristics')),
                ('survey', models.ForeignKey(help_text='Опрос, для которого требуется характеристика', on_delete=django.db.models.deletion.CASCADE, related_name='required_characteristics', to='surveys.surveys')),
            ],
            options={
                'verbose_name': 'Требуемая характеристика опроса',
                'verbose_name_plural': 'Требуемые характеристики опросов',
                'db_table': 'survey_required_characteristics',
                'unique_together': {('survey', 'characteristic')},
            },
        ),
    ]
