# Generated by Django 5.2.6 on 2025-10-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_respondentcharacteristics_score'),
        ('core', '0002_surveyrequiredcharacteristics'),
        ('surveys', '0002_surveys_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyrequiredcharacteristics',
            name='is_required',
        ),
        migrations.AddField(
            model_name='surveyrequiredcharacteristics',
            name='requirements',
            field=models.TextField(blank=True, help_text='Дополнительные условия для характеристики', null=True),
        ),
        migrations.AlterField(
            model_name='surveyrequiredcharacteristics',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_surveys', to='accounts.characteristics'),
        ),
        migrations.AlterField(
            model_name='surveyrequiredcharacteristics',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='surveyrequiredcharacteristics',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_characteristics', to='surveys.surveys'),
        ),
    ]
